spring:
  application:
    name: book_management_mission
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:book_management}
    username: ${DB_USERNAME:book_management}
    password: ${DB_PASSWORD:password}